# Generated by Django 4.2.3 on 2023-09-03 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sending', '0002_mailing_owner_message_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail_sending.message', verbose_name='Сообщение'),
        ),
    ]
